
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 11 2026 11:42:10 IST (Mar 11 2026 06:12:10 UTC)

// Verification Directory fv/uart_auto_baud_top 

module uart_auto_baud_top(clk, rst, rx, data_out, data_valid);
  input clk, rst, rx;
  output [7:0] data_out;
  output data_valid;
  wire clk, rst, rx;
  wire [7:0] data_out;
  wire data_valid;
  wire [15:0] u3_counter;
  wire [15:0] u2_counter;
  wire [15:0] baud_count;
  wire [7:0] u4_shift_reg;
  wire [3:0] u4_state;
  wire [2:0] u2_edge_count;
  wire [2:0] u4_bit_index;
  wire baud_valid, n_0, n_3, n_4, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_41, n_42;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_241;
  wire n_242, n_243, n_244, sample_tick, u1_rx_d1, u1_rx_d2;
  DFFRHQX1 \u3_counter_reg[1] (.RN (n_237), .CK (clk), .D (n_225), .Q
       (u3_counter[1]));
  NOR2XL g4949__2398(.A (n_92), .B (n_234), .Y (n_236));
  NOR2XL g4919__5107(.A (n_198), .B (n_234), .Y (n_235));
  NOR2XL g4947__6260(.A (n_42), .B (n_234), .Y (n_233));
  NOR2XL g4948__4319(.A (u3_counter[0]), .B (n_234), .Y (n_232));
  NOR2XL g4928__8428(.A (n_185), .B (n_234), .Y (n_231));
  NOR2XL g4916__5526(.A (n_210), .B (n_234), .Y (n_230));
  NOR2XL g4950__6783(.A (n_79), .B (n_234), .Y (n_229));
  NOR2XL g4932__3680(.A (n_169), .B (n_234), .Y (n_228));
  NOR2XL g4956__1617(.A (n_139), .B (n_234), .Y (n_227));
  NOR2XL g4953__2802(.A (n_107), .B (n_234), .Y (n_226));
  NOR2XL g4954__1705(.A (n_24), .B (n_234), .Y (n_225));
  NOR2XL g4955__5122(.A (n_121), .B (n_234), .Y (n_224));
  NOR2XL g4952__8246(.A (n_127), .B (n_234), .Y (n_223));
  NOR2XL g4914__7098(.A (n_209), .B (n_234), .Y (n_222));
  NOR2XL g4936__6131(.A (n_159), .B (n_234), .Y (n_221));
  NOR2XL g4924__1881(.A (n_192), .B (n_234), .Y (n_220));
  NAND3X1 g4957__5115(.A (baud_valid), .B (n_56), .C (n_219), .Y
       (n_234));
  AOI222XL g4960__7482(.A0 (n_218), .A1 (n_39), .B0 (n_55), .B1 (n_54),
       .C0 (n_218), .C1 (n_212), .Y (n_219));
  OAI32X1 g4966__4733(.A0 (u2_counter[15]), .A1 (n_215), .A2 (n_213),
       .B0 (n_4), .B1 (n_214), .Y (n_217));
  OAI32X1 g4968__6161(.A0 (u2_counter[14]), .A1 (n_215), .A2 (n_205),
       .B0 (n_203), .B1 (n_207), .Y (n_216));
  AOI21X1 g4973__9315(.A0 (n_206), .A1 (n_213), .B0 (baud_valid), .Y
       (n_214));
  AOI32X1 g4963__9945(.A0 (n_61), .A1 (n_99), .A2 (n_202), .B0
       (baud_count[12]), .B1 (n_191), .Y (n_212));
  OAI32X1 g4974__2883(.A0 (u2_counter[13]), .A1 (n_215), .A2 (n_199),
       .B0 (n_195), .B1 (n_200), .Y (n_211));
  MXI2XL g4918__2346(.A (n_208), .B (n_201), .S0 (u3_counter[14]), .Y
       (n_210));
  AOI21XL g4915__1666(.A0 (u3_counter[14]), .A1 (n_208), .B0
       (u3_counter[15]), .Y (n_209));
  AOI21X1 g4976__7410(.A0 (n_206), .A1 (n_205), .B0 (baud_valid), .Y
       (n_207));
  OAI32X1 g4977__6417(.A0 (u2_counter[12]), .A1 (n_215), .A2 (n_193),
       .B0 (n_186), .B1 (n_194), .Y (n_204));
  OR2X1 g4979__5477(.A (n_203), .B (n_205), .Y (n_213));
  OAI211X1 g4972__2398(.A0 (u3_counter[9]), .A1 (n_25), .B0 (n_98), .C0
       (n_190), .Y (n_202));
  CLKINVX1 g4920(.A (n_201), .Y (n_208));
  AOI21X1 g4978__5107(.A0 (n_206), .A1 (n_199), .B0 (baud_valid), .Y
       (n_200));
  MXI2XL g4922__6260(.A (u3_counter[13]), .B (n_45), .S0 (n_196), .Y
       (n_198));
  OAI32X1 g4981__4319(.A0 (u2_counter[11]), .A1 (n_215), .A2 (n_183),
       .B0 (n_178), .B1 (n_184), .Y (n_197));
  NAND2XL g4923__8428(.A (u3_counter[13]), .B (n_196), .Y (n_201));
  OR2X1 g4992__5526(.A (n_195), .B (n_199), .Y (n_205));
  DFFRHQX1 \u2_counter_reg[1] (.RN (n_237), .CK (clk), .D (n_189), .Q
       (u2_counter[1]));
  AOI21X1 g4991__6783(.A0 (n_206), .A1 (n_193), .B0 (baud_valid), .Y
       (n_194));
  MXI2XL g4926__3680(.A (n_191), .B (u3_counter[12]), .S0 (n_187), .Y
       (n_192));
  AOI32X1 g4982__1617(.A0 (n_66), .A1 (n_85), .A2 (n_168), .B0
       (baud_count[8]), .B1 (n_138), .Y (n_190));
  OAI31XL g5005__2802(.A0 (n_3), .A1 (u2_counter[1]), .A2 (n_215), .B0
       (n_181), .Y (n_189));
  OAI32X1 g4990__1705(.A0 (u2_counter[10]), .A1 (n_215), .A2 (n_170),
       .B0 (n_167), .B1 (n_171), .Y (n_188));
  NOR2XL g4927__5122(.A (n_191), .B (n_187), .Y (n_196));
  OR2X1 g5000__8246(.A (n_186), .B (n_193), .Y (n_199));
  MXI2XL g4930__7098(.A (u3_counter[11]), .B (n_20), .S0 (n_179), .Y
       (n_185));
  AOI21X1 g4997__6131(.A0 (n_206), .A1 (n_183), .B0 (baud_valid), .Y
       (n_184));
  SDFFRHQX1 \u2_counter_reg[0] (.RN (n_237), .CK (clk), .D (n_145), .SI
       (baud_valid), .SE (u2_counter[0]), .Q (u2_counter[0]));
  OAI32XL g4999__1881(.A0 (n_149), .A1 (u2_counter[5]), .A2 (n_215),
       .B0 (n_150), .B1 (n_96), .Y (n_182));
  OAI21XL g5024__5115(.A0 (n_241), .A1 (baud_valid), .B0
       (u2_counter[1]), .Y (n_181));
  OAI32XL g4998__7482(.A0 (n_151), .A1 (u2_counter[3]), .A2 (n_215),
       .B0 (n_152), .B1 (n_52), .Y (n_180));
  NAND2XL g4931__4733(.A (u3_counter[11]), .B (n_179), .Y (n_187));
  OR2X1 g5026__6161(.A (n_178), .B (n_183), .Y (n_193));
  OAI32X1 g5003__9315(.A0 (u2_counter[8]), .A1 (n_215), .A2 (n_153),
       .B0 (n_133), .B1 (n_154), .Y (n_177));
  OAI32X1 g5004__9945(.A0 (u2_counter[9]), .A1 (n_215), .A2 (n_160),
       .B0 (n_143), .B1 (n_161), .Y (n_176));
  OAI32XL g5006__2883(.A0 (n_162), .A1 (u2_counter[2]), .A2 (n_215),
       .B0 (n_163), .B1 (n_29), .Y (n_175));
  OAI32XL g5007__2346(.A0 (n_157), .A1 (u2_counter[4]), .A2 (n_215),
       .B0 (n_158), .B1 (n_81), .Y (n_174));
  OAI32XL g5008__1666(.A0 (n_155), .A1 (u2_counter[6]), .A2 (n_215),
       .B0 (n_156), .B1 (n_108), .Y (n_173));
  OAI32X1 g5009__7410(.A0 (u2_counter[7]), .A1 (n_215), .A2 (n_147),
       .B0 (n_123), .B1 (n_148), .Y (n_172));
  AOI21X1 g5022__6417(.A0 (n_206), .A1 (n_170), .B0 (baud_valid), .Y
       (n_171));
  MXI2XL g4934__5477(.A (n_165), .B (u3_counter[10]), .S0 (n_164), .Y
       (n_169));
  OAI211X1 g5025__2398(.A0 (u3_counter[4]), .A1 (n_14), .B0 (n_84), .C0
       (n_137), .Y (n_168));
  OR2X1 g5050__5107(.A (n_167), .B (n_170), .Y (n_183));
  SDFFRHQX1 \u2_baud_count_reg[0] (.RN (n_237), .CK (clk), .D
       (u2_counter[0]), .SI (baud_count[0]), .SE (n_166), .Q
       (baud_count[0]));
  SDFFRHQX1 \u2_baud_count_reg[1] (.RN (n_237), .CK (clk), .D
       (u2_counter[1]), .SI (baud_count[1]), .SE (n_166), .Q
       (baud_count[1]));
  SDFFRHQX1 \u2_baud_count_reg[10] (.RN (n_237), .CK (clk), .D
       (u2_counter[10]), .SI (baud_count[10]), .SE (n_166), .Q
       (baud_count[10]));
  SDFFRHQX1 \u2_baud_count_reg[2] (.RN (n_237), .CK (clk), .D
       (u2_counter[2]), .SI (baud_count[2]), .SE (n_166), .Q
       (baud_count[2]));
  SDFFRHQX1 \u2_baud_count_reg[11] (.RN (n_237), .CK (clk), .D
       (u2_counter[11]), .SI (baud_count[11]), .SE (n_166), .Q
       (baud_count[11]));
  SDFFRHQX1 \u2_baud_count_reg[7] (.RN (n_237), .CK (clk), .D
       (u2_counter[7]), .SI (baud_count[7]), .SE (n_166), .Q
       (baud_count[7]));
  SDFFRHQX1 u3_sample_tick_reg(.RN (n_237), .CK (clk), .D
       (sample_tick), .SI (n_135), .SE (baud_valid), .Q (sample_tick));
  SDFFRHQX1 \u2_baud_count_reg[6] (.RN (n_237), .CK (clk), .D
       (u2_counter[6]), .SI (baud_count[6]), .SE (n_166), .Q
       (baud_count[6]));
  NOR2XL g4935__6260(.A (n_165), .B (n_164), .Y (n_179));
  SDFFRHQX1 \u2_baud_count_reg[5] (.RN (n_237), .CK (clk), .D
       (u2_counter[5]), .SI (baud_count[5]), .SE (n_166), .Q
       (baud_count[5]));
  SDFFRHQX1 \u2_baud_count_reg[12] (.RN (n_237), .CK (clk), .D
       (u2_counter[12]), .SI (baud_count[12]), .SE (n_166), .Q
       (baud_count[12]));
  SDFFRHQX1 \u2_baud_count_reg[13] (.RN (n_237), .CK (clk), .D
       (u2_counter[13]), .SI (baud_count[13]), .SE (n_166), .Q
       (baud_count[13]));
  SDFFRHQX1 \u2_baud_count_reg[4] (.RN (n_237), .CK (clk), .D
       (u2_counter[4]), .SI (baud_count[4]), .SE (n_166), .Q
       (baud_count[4]));
  SDFFRHQX1 \u2_baud_count_reg[3] (.RN (n_237), .CK (clk), .D
       (u2_counter[3]), .SI (baud_count[3]), .SE (n_166), .Q
       (baud_count[3]));
  SDFFRHQX1 \u2_baud_count_reg[15] (.RN (n_237), .CK (clk), .D
       (u2_counter[15]), .SI (baud_count[15]), .SE (n_166), .Q
       (baud_count[15]));
  SDFFRHQX1 \u2_baud_count_reg[14] (.RN (n_237), .CK (clk), .D
       (u2_counter[14]), .SI (baud_count[14]), .SE (n_166), .Q
       (baud_count[14]));
  SDFFRHQX1 \u2_baud_count_reg[8] (.RN (n_237), .CK (clk), .D
       (u2_counter[8]), .SI (baud_count[8]), .SE (n_166), .Q
       (baud_count[8]));
  SDFFRHQX1 \u2_baud_count_reg[9] (.RN (n_237), .CK (clk), .D
       (u2_counter[9]), .SI (baud_count[9]), .SE (n_166), .Q
       (baud_count[9]));
  AOI21X1 g5043__4319(.A0 (n_162), .A1 (n_206), .B0 (baud_valid), .Y
       (n_163));
  AOI21X1 g5042__8428(.A0 (n_206), .A1 (n_160), .B0 (baud_valid), .Y
       (n_161));
  MXI2XL g4942__5526(.A (u3_counter[9]), .B (n_62), .S0 (n_144), .Y
       (n_159));
  AOI21X1 g5044__6783(.A0 (n_157), .A1 (n_206), .B0 (baud_valid), .Y
       (n_158));
  AOI21X1 g5045__3680(.A0 (n_206), .A1 (n_155), .B0 (baud_valid), .Y
       (n_156));
  AOI21X1 g5046__1617(.A0 (n_206), .A1 (n_153), .B0 (baud_valid), .Y
       (n_154));
  AOI21X1 g5047__2802(.A0 (n_151), .A1 (n_206), .B0 (baud_valid), .Y
       (n_152));
  AOI21X1 g5048__1705(.A0 (n_149), .A1 (n_206), .B0 (baud_valid), .Y
       (n_150));
  AOI21X1 g5049__5122(.A0 (n_206), .A1 (n_147), .B0 (baud_valid), .Y
       (n_148));
  INVXL g5055(.A (n_215), .Y (n_145));
  NAND2XL g4951__7098(.A (u3_counter[9]), .B (n_144), .Y (n_164));
  OR2X1 g5054__6131(.A (n_143), .B (n_160), .Y (n_170));
  NAND2XL g5057__1881(.A (n_141), .B (n_166), .Y (n_142));
  NAND2XL g5059__5115(.A (n_141), .B (n_206), .Y (n_215));
  SDFFQX1 \u4_shift_reg_reg[1] (.CK (clk), .D (rx), .SI
       (u4_shift_reg[1]), .SE (n_119), .Q (u4_shift_reg[1]));
  SDFFQX1 \u4_shift_reg_reg[3] (.CK (clk), .D (rx), .SI
       (u4_shift_reg[3]), .SE (n_116), .Q (u4_shift_reg[3]));
  SDFFRHQX1 \u4_state_reg[1] (.RN (n_237), .CK (clk), .D (n_68), .SI
       (u4_state[1]), .SE (n_140), .Q (u4_state[1]));
  SDFFRHQX1 \u4_state_reg[0] (.RN (n_237), .CK (clk), .D (n_71), .SI
       (u4_state[0]), .SE (n_140), .Q (u4_state[0]));
  SDFFRHQX1 \u4_state_reg[2] (.RN (n_237), .CK (clk), .D (n_89), .SI
       (u4_state[2]), .SE (n_140), .Q (u4_state[2]));
  MXI2XL g4958__7482(.A (n_138), .B (u3_counter[8]), .S0 (n_134), .Y
       (n_139));
  OAI21X1 g5058__4733(.A0 (baud_count[3]), .A1 (n_130), .B0 (n_131), .Y
       (n_137));
  SDFFQX1 \u4_shift_reg_reg[2] (.CK (clk), .D (u4_shift_reg[2]), .SI
       (rx), .SE (n_117), .Q (u4_shift_reg[2]));
  SDFFQX1 \u4_shift_reg_reg[0] (.CK (clk), .D (u4_shift_reg[0]), .SI
       (rx), .SE (n_120), .Q (u4_shift_reg[0]));
  DFFRHQX1 \u2_edge_count_reg[1] (.RN (n_237), .CK (clk), .D (n_129),
       .Q (u2_edge_count[1]));
  NOR4X1 g5056__6161(.A (u3_counter[15]), .B (n_76), .C (n_73), .D
       (n_122), .Y (n_135));
  SDFFQX1 \u4_shift_reg_reg[6] (.CK (clk), .D (rx), .SI
       (u4_shift_reg[6]), .SE (n_113), .Q (u4_shift_reg[6]));
  SDFFQX1 \u4_shift_reg_reg[4] (.CK (clk), .D (rx), .SI
       (u4_shift_reg[4]), .SE (n_110), .Q (u4_shift_reg[4]));
  NOR2XL g4959__9315(.A (n_138), .B (n_134), .Y (n_144));
  OR2X1 g5070__9945(.A (n_133), .B (n_153), .Y (n_160));
  NAND2BX1 g5072__2883(.AN (u2_edge_count[0]), .B (n_132), .Y (n_206));
  NAND2X1 g5073__2346(.A (u2_edge_count[0]), .B (n_132), .Y (n_166));
  SDFFQX1 \u4_shift_reg_reg[7] (.CK (clk), .D (u4_shift_reg[7]), .SI
       (rx), .SE (n_104), .Q (u4_shift_reg[7]));
  SDFFQX1 \u4_shift_reg_reg[5] (.CK (clk), .D (rx), .SI
       (u4_shift_reg[5]), .SE (n_106), .Q (u4_shift_reg[5]));
  SDFFRHQX1 \u2_edge_count_reg[0] (.RN (n_237), .CK (clk), .D (n_126),
       .SI (n_128), .SE (u2_edge_count[0]), .Q (u2_edge_count[0]));
  OAI2BB1X1 g5069__1666(.A0N (baud_count[3]), .A1N (n_130), .B0
       (u3_counter[3]), .Y (n_131));
  OAI2BB1XL g5074__7410(.A0N (u2_edge_count[1]), .A1N (n_128), .B0
       (n_114), .Y (n_129));
  MXI2XL g4961__6417(.A (u3_counter[7]), .B (n_47), .S0 (n_124), .Y
       (n_127));
  SDFFRHQX1 \u2_edge_count_reg[2] (.RN (n_237), .CK (clk), .D
       (u2_edge_count[2]), .SI (n_58), .SE (n_126), .Q
       (u2_edge_count[2]));
  SDFFRHQX1 \u4_bit_index_reg[2] (.RN (n_237), .CK (clk), .D (n_80),
       .SI (u4_bit_index[2]), .SE (n_125), .Q (u4_bit_index[2]));
  SDFFRHQX1 \u4_bit_index_reg[0] (.RN (n_237), .CK (clk), .D (n_78),
       .SI (u4_bit_index[0]), .SE (n_125), .Q (u4_bit_index[0]));
  NOR3X1 g5083__5477(.A (u2_edge_count[1]), .B (u2_edge_count[2]), .C
       (n_128), .Y (n_132));
  NAND2XL g4964__2398(.A (u3_counter[7]), .B (n_124), .Y (n_134));
  OR2X1 g5078__5107(.A (n_123), .B (n_147), .Y (n_153));
  SDFFRHQX1 \u4_bit_index_reg[1] (.RN (n_237), .CK (clk), .D (n_74),
       .SI (u4_bit_index[1]), .SE (n_125), .Q (u4_bit_index[1]));
  NAND4XL g5068__6260(.A (n_48), .B (n_17), .C (n_27), .D (n_100), .Y
       (n_122));
  MXI2XL g4969__4319(.A (n_112), .B (u3_counter[6]), .S0 (n_111), .Y
       (n_121));
  NOR2XL g5075__8428(.A (u4_bit_index[0]), .B (n_118), .Y (n_120));
  AOI211X1 g5071__5526(.A0 (sample_tick), .A1 (n_94), .B0 (n_93), .C0
       (n_75), .Y (n_140));
  NAND2BXL g5081__6783(.AN (n_118), .B (u4_bit_index[0]), .Y (n_119));
  NOR2BX1 g5080__3680(.AN (n_115), .B (u4_bit_index[0]), .Y (n_117));
  NAND2XL g5076__1617(.A (u4_bit_index[0]), .B (n_115), .Y (n_116));
  OAI211X1 g5089__2802(.A0 (u2_edge_count[0]), .A1 (u2_edge_count[1]),
       .B0 (n_126), .C0 (n_57), .Y (n_114));
  NAND3X1 g5079__1705(.A (u4_bit_index[2]), .B (n_109), .C (n_103), .Y
       (n_113));
  NOR2XL g4970__5122(.A (n_112), .B (n_111), .Y (n_124));
  NAND3X1 g5082__8246(.A (u4_bit_index[2]), .B (n_109), .C (n_105), .Y
       (n_110));
  AOI21X1 g5091__7098(.A0 (u3_counter[2]), .A1 (n_16), .B0 (n_95), .Y
       (n_130));
  OR2X1 g5087__6131(.A (n_108), .B (n_155), .Y (n_147));
  MXI2XL g4983__1881(.A (u3_counter[5]), .B (n_46), .S0 (n_97), .Y
       (n_107));
  NAND2BXL g5084__5115(.AN (n_102), .B (n_105), .Y (n_106));
  NOR2BX1 g5085__7482(.AN (n_103), .B (n_102), .Y (n_104));
  NAND2XL g5086__4733(.A (n_101), .B (n_105), .Y (n_118));
  AND2X1 g5092__6161(.A (n_101), .B (n_103), .Y (n_115));
  CLKINVX1 g5103(.A (n_126), .Y (n_128));
  AOI211XL g5090__9315(.A0 (u3_counter[0]), .A1 (n_82), .B0 (n_15), .C0
       (n_72), .Y (n_100));
  AOI32X1 g5088__9945(.A0 (n_44), .A1 (n_98), .A2 (n_63), .B0 (n_60),
       .B1 (n_59), .Y (n_99));
  NAND2XL g4993__2883(.A (u3_counter[5]), .B (n_97), .Y (n_111));
  OR2X1 g5101__2346(.A (n_96), .B (n_149), .Y (n_155));
  AOI21X1 g5107__1666(.A0 (baud_count[2]), .A1 (n_41), .B0 (n_83), .Y
       (n_95));
  INVXL g5102(.A (n_91), .Y (n_94));
  AOI31X1 g5112__7410(.A0 (sample_tick), .A1 (n_51), .A2 (n_90), .B0
       (n_93), .Y (n_125));
  AOI211X1 g5113__6417(.A0 (u1_rx_d2), .A1 (u1_rx_d1), .B0 (n_69), .C0
       (baud_valid), .Y (n_126));
  MXI2XL g5023__5477(.A (n_87), .B (u3_counter[4]), .S0 (n_86), .Y
       (n_92));
  AOI211X1 g5108__2398(.A0 (n_50), .A1 (n_90), .B0 (n_89), .C0 (n_244),
       .Y (n_91));
  NOR3X1 g5110__5107(.A (u4_state[2]), .B (u4_bit_index[1]), .C (n_88),
       .Y (n_105));
  NOR3X1 g5111__6260(.A (u4_state[2]), .B (n_31), .C (n_88), .Y
       (n_103));
  SDFFRHQX1 \u4_data_out_reg[3] (.RN (n_237), .CK (clk), .D
       (data_out[3]), .SI (u4_shift_reg[3]), .SE (n_93), .Q
       (data_out[3]));
  NOR2XL g5040__4319(.A (n_87), .B (n_86), .Y (n_97));
  SDFFRHQX1 \u4_data_out_reg[2] (.RN (n_237), .CK (clk), .D
       (data_out[2]), .SI (u4_shift_reg[2]), .SE (n_93), .Q
       (data_out[2]));
  SDFFRHQX1 \u4_data_out_reg[4] (.RN (n_237), .CK (clk), .D
       (data_out[4]), .SI (u4_shift_reg[4]), .SE (n_93), .Q
       (data_out[4]));
  SDFFRHQX1 \u4_data_out_reg[5] (.RN (n_237), .CK (clk), .D
       (data_out[5]), .SI (u4_shift_reg[5]), .SE (n_93), .Q
       (data_out[5]));
  SDFFRHQX1 \u4_data_out_reg[1] (.RN (n_237), .CK (clk), .D
       (data_out[1]), .SI (u4_shift_reg[1]), .SE (n_93), .Q
       (data_out[1]));
  AOI22X1 g5105__8428(.A0 (n_38), .A1 (n_84), .B0 (n_65), .B1 (n_64),
       .Y (n_85));
  AOI22X1 g5115__5526(.A0 (u3_counter[1]), .A1 (n_49), .B0 (n_82), .B1
       (n_9), .Y (n_83));
  SDFFRHQX1 \u4_data_out_reg[0] (.RN (n_237), .CK (clk), .D
       (data_out[0]), .SI (u4_shift_reg[0]), .SE (n_93), .Q
       (data_out[0]));
  SDFFRHQX1 \u4_data_out_reg[6] (.RN (n_237), .CK (clk), .D
       (data_out[6]), .SI (u4_shift_reg[6]), .SE (n_93), .Q
       (data_out[6]));
  SDFFRHQX1 \u4_data_out_reg[7] (.RN (n_237), .CK (clk), .D
       (data_out[7]), .SI (u4_shift_reg[7]), .SE (n_93), .Q
       (data_out[7]));
  OR2X1 g5117__6783(.A (n_81), .B (n_157), .Y (n_149));
  AOI21X1 g5104__3680(.A0 (n_101), .A1 (n_7), .B0 (n_77), .Y (n_80));
  MXI2XL g5067__1617(.A (u3_counter[3]), .B (n_13), .S0 (n_53), .Y
       (n_79));
  NOR2XL g5132__2802(.A (u4_bit_index[0]), .B (n_77), .Y (n_78));
  NAND3X1 g5118__1705(.A (n_35), .B (n_11), .C (n_19), .Y (n_76));
  NOR3X1 g5119__5122(.A (n_141), .B (rx), .C (n_70), .Y (n_75));
  NOR2XL g5120__8246(.A (n_33), .B (n_77), .Y (n_74));
  NAND4XL g5121__7098(.A (n_26), .B (n_23), .C (n_21), .D (n_22), .Y
       (n_73));
  NAND4XL g5122__6131(.A (n_37), .B (n_32), .C (n_36), .D (n_18), .Y
       (n_72));
  NAND2XL g5124__1881(.A (n_70), .B (n_77), .Y (n_71));
  NOR2XL g5125__5115(.A (u1_rx_d2), .B (u1_rx_d1), .Y (n_69));
  NAND2BXL g5126__7482(.AN (n_244), .B (n_77), .Y (n_68));
  OAI21X1 g5131__4733(.A0 (n_65), .A1 (n_64), .B0 (u3_counter[7]), .Y
       (n_66));
  OAI21X1 g5130__6161(.A0 (baud_count[9]), .A1 (n_243), .B0 (n_62), .Y
       (n_63));
  OAI21X1 g5129__9315(.A0 (n_60), .A1 (n_59), .B0 (u3_counter[11]), .Y
       (n_61));
  CLKINVX1 g5137(.A (n_77), .Y (n_90));
  NAND3X1 g5135__9945(.A (sample_tick), .B (n_242), .C (n_237), .Y
       (n_88));
  OAI21X1 g5109__2883(.A0 (u2_edge_count[2]), .A1 (n_57), .B0 (n_12),
       .Y (n_58));
  OAI21X1 g5127__2346(.A0 (n_55), .A1 (n_54), .B0 (u3_counter[15]), .Y
       (n_56));
  DFFRHQX1 u4_data_valid_reg(.RN (n_237), .CK (clk), .D (n_93), .Q
       (data_valid));
  NAND2XL g5077__1666(.A (u3_counter[3]), .B (n_53), .Y (n_86));
  OR2X1 g5128__7410(.A (n_52), .B (n_151), .Y (n_157));
  INVXL g5136(.A (n_50), .Y (n_51));
  NAND2BX1 g5140__6417(.AN (n_48), .B (baud_count[0]), .Y (n_49));
  AOI222XL g5133__5477(.A0 (baud_count[7]), .A1 (n_47), .B0
       (baud_count[6]), .B1 (n_112), .C0 (n_46), .C1 (baud_count[5]),
       .Y (n_84));
  AOI222XL g5134__2398(.A0 (baud_count[15]), .A1 (n_0), .B0
       (baud_count[14]), .B1 (n_34), .C0 (n_45), .C1 (baud_count[13]),
       .Y (n_218));
  NAND2XL g5143__5107(.A (baud_count[9]), .B (n_243), .Y (n_44));
  MXI2XL g5106__6260(.A (n_41), .B (u3_counter[2]), .S0 (n_10), .Y
       (n_42));
  DFFSHQX1 u1_rx_d2_reg(.SN (n_237), .CK (clk), .D (u1_rx_d1), .Q
       (u1_rx_d2));
  NAND2XL g5150__4319(.A (n_30), .B (n_242), .Y (n_77));
  OAI22X1 g5138__8428(.A0 (baud_count[13]), .A1 (n_45), .B0
       (baud_count[12]), .B1 (n_191), .Y (n_39));
  OAI22X1 g5139__5526(.A0 (baud_count[5]), .A1 (n_46), .B0
       (baud_count[4]), .B1 (n_87), .Y (n_38));
  OAI22X1 g5141__6783(.A0 (baud_count[7]), .A1 (u3_counter[6]), .B0
       (n_65), .B1 (n_112), .Y (n_37));
  MXI2XL g5142__3680(.A (u3_counter[5]), .B (n_46), .S0
       (baud_count[6]), .Y (n_36));
  AOI22X1 g5154__1617(.A0 (baud_count[15]), .A1 (n_34), .B0
       (u3_counter[14]), .B1 (n_55), .Y (n_35));
  MXI2XL g5153__2802(.A (u4_bit_index[0]), .B (n_109), .S0
       (u4_bit_index[1]), .Y (n_33));
  MXI2XL g5152__1705(.A (u3_counter[7]), .B (n_47), .S0
       (baud_count[8]), .Y (n_32));
  NOR2XL g5146__5122(.A (u4_state[2]), .B (n_6), .Y (n_89));
  NOR2XL g5148__8246(.A (n_31), .B (n_102), .Y (n_50));
  NAND2XL g5144__7098(.A (n_30), .B (n_28), .Y (n_70));
  OR2X1 g5149__1881(.A (n_29), .B (n_162), .Y (n_151));
  AND2X1 g5151__5115(.A (u4_state[2]), .B (n_28), .Y (n_93));
  MXI2XL g5163__7482(.A (u3_counter[2]), .B (n_41), .S0
       (baud_count[3]), .Y (n_27));
  MXI2XL g5157__4733(.A (baud_count[9]), .B (n_25), .S0
       (u3_counter[8]), .Y (n_26));
  MXI2XL g5158__6161(.A (u3_counter[0]), .B (n_8), .S0 (u3_counter[1]),
       .Y (n_24));
  MXI2XL g5160__9315(.A (u3_counter[10]), .B (n_165), .S0
       (baud_count[11]), .Y (n_23));
  MXI2XL g5161__9945(.A (u3_counter[9]), .B (n_62), .S0
       (baud_count[10]), .Y (n_22));
  MXI2XL g5162__2883(.A (u3_counter[11]), .B (n_20), .S0
       (baud_count[12]), .Y (n_21));
  MXI2XL g5156__2346(.A (u3_counter[12]), .B (n_191), .S0
       (baud_count[13]), .Y (n_19));
  MXI2XL g5164__1666(.A (u3_counter[4]), .B (n_87), .S0
       (baud_count[5]), .Y (n_18));
  MXI2XL g5165__7410(.A (baud_count[2]), .B (n_16), .S0
       (u3_counter[1]), .Y (n_17));
  OAI22X1 g5159__6417(.A0 (u3_counter[3]), .A1 (n_14), .B0 (n_13), .B1
       (baud_count[4]), .Y (n_15));
  NAND2XL g5114__5477(.A (u2_edge_count[2]), .B (n_57), .Y (n_12));
  MXI2XL g5155__2398(.A (u3_counter[13]), .B (n_45), .S0
       (baud_count[14]), .Y (n_11));
  AOI22X1 g5166__5107(.A0 (baud_count[11]), .A1 (n_20), .B0
       (baud_count[10]), .B1 (n_165), .Y (n_98));
  NOR2XL g5116__6260(.A (n_41), .B (n_10), .Y (n_53));
  NAND2XL g5174__4319(.A (baud_count[0]), .B (n_8), .Y (n_9));
  NAND2XL g5168__8428(.A (baud_count[1]), .B (n_8), .Y (n_48));
  DFFSHQX1 u1_rx_d1_reg(.SN (n_237), .CK (clk), .D (rx), .Q (u1_rx_d1));
  NOR2XL g5180__6783(.A (baud_count[10]), .B (n_165), .Y (n_59));
  NOR2XL g5179__3680(.A (baud_count[6]), .B (n_112), .Y (n_64));
  NOR2XL g5178__1617(.A (baud_count[14]), .B (n_34), .Y (n_54));
  NOR2XL g5167__1705(.A (u4_state[0]), .B (u4_state[1]), .Y (n_28));
  NAND2XL g5169__5122(.A (u3_counter[0]), .B (u3_counter[1]), .Y
       (n_10));
  NAND2XL g5170__8246(.A (u2_counter[0]), .B (u2_counter[1]), .Y
       (n_162));
  NAND2XL g5175__7098(.A (u4_bit_index[1]), .B (u4_bit_index[0]), .Y
       (n_7));
  NAND2XL g5176__6131(.A (u4_state[0]), .B (u4_state[1]), .Y (n_6));
  NAND2XL g5172__1881(.A (u4_bit_index[0]), .B (u4_bit_index[2]), .Y
       (n_102));
  NAND2XL g5171__5115(.A (u2_edge_count[0]), .B (u2_edge_count[1]), .Y
       (n_57));
  CLKINVX1 g5190(.A (baud_count[4]), .Y (n_14));
  CLKINVX1 g5193(.A (baud_count[11]), .Y (n_60));
  CLKINVX1 g5203(.A (u4_bit_index[1]), .Y (n_31));
  CLKINVX1 g5194(.A (baud_count[9]), .Y (n_25));
  CLKINVX1 g5225(.A (u4_state[2]), .Y (n_30));
  CLKINVX1 g5218(.A (baud_count[7]), .Y (n_65));
  CLKINVX1 g5200(.A (u4_bit_index[2]), .Y (n_101));
  CLKINVX1 g5226(.A (u4_bit_index[0]), .Y (n_109));
  CLKINVX1 g5207(.A (rst), .Y (n_237));
  INVXL g5196(.A (u2_counter[0]), .Y (n_3));
  CLKINVX1 g5189(.A (baud_count[1]), .Y (n_82));
  CLKINVX1 g5192(.A (baud_count[2]), .Y (n_16));
  CLKINVX1 g5195(.A (baud_count[15]), .Y (n_55));
  DFFRX1 \u2_counter_reg[15] (.RN (n_237), .CK (clk), .D (n_217), .Q
       (u2_counter[15]), .QN (n_4));
  DFFRX1 \u2_counter_reg[11] (.RN (n_237), .CK (clk), .D (n_197), .Q
       (u2_counter[11]), .QN (n_178));
  DFFRX1 \u2_counter_reg[12] (.RN (n_237), .CK (clk), .D (n_204), .Q
       (u2_counter[12]), .QN (n_186));
  DFFRX1 \u2_counter_reg[6] (.RN (n_237), .CK (clk), .D (n_173), .Q
       (u2_counter[6]), .QN (n_108));
  DFFRX1 \u2_counter_reg[4] (.RN (n_237), .CK (clk), .D (n_174), .Q
       (u2_counter[4]), .QN (n_81));
  DFFRX1 \u2_counter_reg[5] (.RN (n_237), .CK (clk), .D (n_182), .Q
       (u2_counter[5]), .QN (n_96));
  DFFRX1 \u2_counter_reg[8] (.RN (n_237), .CK (clk), .D (n_177), .Q
       (u2_counter[8]), .QN (n_133));
  DFFRX1 \u2_counter_reg[10] (.RN (n_237), .CK (clk), .D (n_188), .Q
       (u2_counter[10]), .QN (n_167));
  DFFRX1 \u3_counter_reg[0] (.RN (n_237), .CK (clk), .D (n_232), .Q
       (u3_counter[0]), .QN (n_8));
  DFFRX1 \u3_counter_reg[5] (.RN (n_237), .CK (clk), .D (n_226), .Q
       (u3_counter[5]), .QN (n_46));
  DFFRX1 \u3_counter_reg[12] (.RN (n_237), .CK (clk), .D (n_220), .Q
       (u3_counter[12]), .QN (n_191));
  DFFRX1 \u3_counter_reg[10] (.RN (n_237), .CK (clk), .D (n_228), .Q
       (u3_counter[10]), .QN (n_165));
  DFFRX1 \u3_counter_reg[6] (.RN (n_237), .CK (clk), .D (n_224), .Q
       (u3_counter[6]), .QN (n_112));
  DFFRX1 \u3_counter_reg[15] (.RN (n_237), .CK (clk), .D (n_222), .Q
       (u3_counter[15]), .QN (n_0));
  DFFRX1 \u2_counter_reg[13] (.RN (n_237), .CK (clk), .D (n_211), .Q
       (u2_counter[13]), .QN (n_195));
  DFFRX1 \u2_counter_reg[2] (.RN (n_237), .CK (clk), .D (n_175), .Q
       (u2_counter[2]), .QN (n_29));
  DFFRX1 \u2_counter_reg[3] (.RN (n_237), .CK (clk), .D (n_180), .Q
       (u2_counter[3]), .QN (n_52));
  DFFRX1 \u2_counter_reg[7] (.RN (n_237), .CK (clk), .D (n_172), .Q
       (u2_counter[7]), .QN (n_123));
  DFFRX1 \u3_counter_reg[3] (.RN (n_237), .CK (clk), .D (n_229), .Q
       (u3_counter[3]), .QN (n_13));
  DFFRX1 \u2_counter_reg[9] (.RN (n_237), .CK (clk), .D (n_176), .Q
       (u2_counter[9]), .QN (n_143));
  DFFRX1 \u2_counter_reg[14] (.RN (n_237), .CK (clk), .D (n_216), .Q
       (u2_counter[14]), .QN (n_203));
  DFFRX1 \u3_counter_reg[8] (.RN (n_237), .CK (clk), .D (n_227), .Q
       (u3_counter[8]), .QN (n_138));
  DFFRX1 \u3_counter_reg[9] (.RN (n_237), .CK (clk), .D (n_221), .Q
       (u3_counter[9]), .QN (n_62));
  DFFRX1 \u3_counter_reg[14] (.RN (n_237), .CK (clk), .D (n_230), .Q
       (u3_counter[14]), .QN (n_34));
  DFFRX1 \u3_counter_reg[11] (.RN (n_237), .CK (clk), .D (n_231), .Q
       (u3_counter[11]), .QN (n_20));
  DFFRX1 u2_baud_valid_reg(.RN (n_237), .CK (clk), .D (n_142), .Q
       (baud_valid), .QN (n_141));
  DFFRX1 \u3_counter_reg[7] (.RN (n_237), .CK (clk), .D (n_223), .Q
       (u3_counter[7]), .QN (n_47));
  DFFRX1 \u3_counter_reg[4] (.RN (n_237), .CK (clk), .D (n_236), .Q
       (u3_counter[4]), .QN (n_87));
  DFFRX1 \u3_counter_reg[13] (.RN (n_237), .CK (clk), .D (n_235), .Q
       (u3_counter[13]), .QN (n_45));
  DFFRX1 \u3_counter_reg[2] (.RN (n_237), .CK (clk), .D (n_233), .Q
       (u3_counter[2]), .QN (n_41));
  NOR2BXL g2(.AN (n_206), .B (u2_counter[0]), .Y (n_241));
  NOR2BX1 g5366(.AN (u4_state[1]), .B (u4_state[0]), .Y (n_242));
  NAND2BX1 g5367(.AN (baud_count[8]), .B (u3_counter[8]), .Y (n_243));
  NOR3BX1 g5368(.AN (u4_state[0]), .B (u4_state[2]), .C (u4_state[1]),
       .Y (n_244));
endmodule

